name: Install pkg

# see: https://help.github.com/en/actions/reference/events-that-trigger-workflows
on:  # Trigger the workflow on push or pull request, but only for the master branch
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  check-package:
    uses: Lightning-AI/utilities/.github/workflows/check-package.yml@main
    with:
      actions-ref: main
      artifact-name: dist-packages-${{ github.sha }}
      import-name: "quick_start"
      testing-matrix: |
        {
          "os": ["ubuntu-22.04", "macos-113", "windows-2022"],
          "python-version": ["3.10"]
        }
